name: 2025_IsaacAgent_
channels:
- conda-forge
dependencies:
- python=3.13.2
- pygame
- pyyaml
- pip
- pip:
  - filelock==3.13.1
  - fsspec==2024.6.1
  - Jinja2==3.1.4
  - MarkupSafe==2.1.5
  - mpmath==1.3.0
  - networkx==3.3
  - numpy==2.1.2
  - pillow==11.0.0
  - setuptools==70.2.0
  - sympy==1.13.1
  - typing_extensions==4.12.2
  - --index-url https://download.pytorch.org/whl/cu126
  - torch==2.6.0+cu126
  - torchvision==0.21.0+cu126
  - torchaudio==2.6.0+cu126
